script:
  rake test --trace

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0

notifications:
  irc: "irc.freenode.org#pry"
  recipients:
    - chris@ill-logic.com

branches:
  only:
    - master
